[package]
name = "el-std-rs"
version = "0.1.0"
authors = ["melektron"]
edition = "2024"
license = "Apache-2.0"
description = "An assortment of useful rust utilities complementing some builtin and third party rust crates"
homepage = "https://github.com/melektron/el_std_rs"
repository = "https://github.com/melektron/el_std_rs"
readme = "README.md"

[dependencies]
el-std-rs-macros = { version = "0.1.0", path = "../el_std_rs_macros" }
anstyle = "1.0.14"
anyhow = "1.0.103"
clap = "4.6.1"
env_logger = "0.11.11"
log = "0.4.33"
rustyline-async = "0.4.9"
shell-words = "1.1.1"
tokio = { version = "1.52.3", features = ["full"] }
tokio-util = "0.7.18"

[dev-dependencies]
testing_logger = "0.1.1"
